#!/usr/bin/env bash

if [ -d "devenv/bin" ]
then
    echo "Virtualenv already installed. Skipping config. Run rm -fr examples/bin to nuke it"
else
    virtualenv -p python3 devenv
fi

cd devenv
source bin/activate
pip install ../
