#!/usr/bin/env python

from gpioone import *

import random
import unscii

if __name__ == "__main__":
    ssd = SSD1306()

    print("Clearing Screen")
    ssd.clear_screen()
    sleep(1)

    print("Testing Print Functions")
    for i in range(0,4):
        string = "Page %d." % i
        for j in range(i):
            string += "."


        ssd.print_line(string,row=i,column=i)

    sleep(5)

    print("TESTING PARTIAL UPDATE")
    ssd.clear_screen()
    ssd.print_line("T Minus 11!",row=2,column=0)
    for i in range(10):
        sleep(0.1)
        ssd.print_string("%d   " % (10 - i), row=2, column=len("T Minus "))

    ssd.clear_screen()
    print("Random Bytes")
    for i in range(4):
        ssd.set_row_and_column(i,0)
        for j in range(16):
            ssd.print_bytes(random.sample(range(256),8))
            sleep(0.1)

    print("Normal UNSCII Fonts")
    for font in unscii.fonts():
        ssd.set_font(font)
        if (ssd.unscii.size() == 1) and ssd.unscii.transposed():
            ssd.print_line("UNSCII Font...",row=0,column=0)
            ssd.print_line(font.replace("_transposed", "").replace("_", " "),row=1,column=0)
            ssd.print_line("abcdefghABCDEFGH",row=2,column=0)
            ssd.print_line("1234567890!@#$%^",row=3,column=0)
            sleep(5)
                       
    print("Double High UNSCII Fonts")
    for font in unscii.fonts():
        ssd.set_font(font)

        if (ssd.unscii.size() == 2) and ssd.unscii.transposed():
            print(font)

            ssd.print_line("UNSCII Font...",row=0,column=0)
            ssd.print_line(font.replace("_transposed", "").replace("_", " "),row=2,column=0)
            sleep(5)
                       
        
    # STILL NEED SOME API WORK
    print("SCROLL TESTS")
    ssd.set_font("unscii_8_mcr_transposed")
    ssd.clear_screen()
    ssd.print_string("SCROLLING",row=0,column=4)
    ssd.print_string("IS",row=1,column=7)
    ssd.print_string("FUN",row=2,column=8)
    ssd.print_string("BUSINESS", row=3,column=4)
    ssd.send_command("RIGHT_HORIZONTAL_SCROLL", 0x0, 0x0, 0x0, 0x7, 0x0, 0xff)
    ssd.activate_scroll()
    sleep(3)
    ssd.deactivate_scroll()
    ssd.send_command("LEFT_HORIZONTAL_SCROLL", 0x0, 0x0, 0x0, 0x7, 0x0, 0xff)
    ssd.activate_scroll()
    sleep(3)
    ssd.deactivate_scroll()
    ssd.send_command("LEFT_HORIZONTAL_SCROLL", 0x0, 0x0, 0x0, 0x7, 0x0, 0xff)
    ssd.send_command("VERTICAL_AND_RIGHT_HORIZONTAL_SCROLL", 0x0, 0x0, 0x0, 0x7, 0x01)
    ssd.activate_scroll()
    sleep(3)
    ssd.deactivate_scroll()
    print("GOODBYE")
