#!/usr/bin/env python

from gpioone import *

if __name__ == "__main__":
    pca = PCA9685()
    pca.servo_mode()

    try:
        while 1:
            for i in range(0,180,5):
                pca.set_servo(0, i)
                sleep(0.1)
    except KeyboardInterrupt:
        pass
